//! The design sheet's resolved geometry, as data. GENERATED — do not hand-edit.
//!
//! Regenerated by `reference.mjs` from `sketch/tool-marks.html`. Every glyph in the sketch set
//! is a hand transposition of a drawing on that sheet: the sheet carries the geometry and the
//! argument for it, the glyph file carries the prose, and neither is compiled from the other.
//! This table is what makes a transposition slip a test failure rather than a subtly wrong icon.
//!
//! Coordinates are the sheet's 36-unit canvas halved onto the glyph grid. Arcs arrive in
//! endpoint form and are converted here by the SVG 1.1 F.6.5 centre formula, because the large
//! and sweep flags interact and a sign heuristic gets a plausible wrong answer.

use super::{Ink, Mark};

/// Kebab id -> the marks that id's glyph must draw, in order.
///
/// Left unformatted on purpose: the layout is the generator's, so a rustfmt pass would make
/// regeneration and formatting two steps that have to be run in the right order.
#[rustfmt::skip]
pub(super) const REFERENCE: &[(&str, &[Mark])] = &[
    // Line — 2 points
    ("line", &[
        Mark::Line { points: &[(2.3, 13.79), (11.8785, 4.2115)], ink: Ink::SOLID },
        Mark::Arc { center: (13.9998, 6.3328), rx: 3.0, ry: 3.0, from: -2.356192, to: 1.832599, ink: Ink::SOLID },
        Mark::Node { center: (2.3, 13.79), size: 2.6, ink: Ink::ACCENT },
        Mark::Node { center: (11.8785, 4.2115), size: 2.6, ink: Ink::ACCENT },
        Mark::Node { center: (13.2233, 9.2306), size: 2.6, ink: Ink::ACCENT },
    ]),
];
